# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: kdump-utils.spec

# add or remove files that should be synced
files_to_sync:
    - kdump-utils.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: kdump-utils
# downstream (Fedora) RPM package name
downstream_package_name: kdump-utils

upstream_tag_template: v{version}


jobs:
  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-all


  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all
    packages:
      - kdump-utils
