# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: kdump-utils.spec

# add or remove files that should be synced
files_to_sync:
    - kdump-utils.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: kdump-utils
# downstream (Fedora) RPM package name
downstream_package_name: kdump-utils

upstream_tag_template: v{version}


jobs:
  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-all


  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-41-x86_64
      - fedora-rawhide-x86_64
    packages:
      - kdump-utils

  - job: tests
    trigger: pull_request
    targets:
      - fedora-41-x86_64
    tmt_plan: nfs_fips$
    fmf_path: kernel-tests-plans
    use_internal_tf: true
    tf_extra_params:
      environments:
        - variables:
            # use internal NFS/SSH server to avoid creating another VM as NFS/SSH server
            RESOURCE_URL: https://gitlab.cee.redhat.com/kernel-qe/kernel/-/raw/master/kdump/internal/internal_resources.sh
            AUTO_CONFIG: auto
            SUBMITTER: rhkdump_kdump_utils_packit
        - settings:
            provisioning:
            # report cloud costs: https://docs.testing-farm.io/Testing%20Farm/0.1/services.html#_changing_the_team_name
              tags:
                BusinessUnit: sst_kernel_debug_sst

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-all
