#!/bin/bash --norc
# Generate an initramfs image that isolates dump capture capability within
# the default initramfs using zz-fadumpinit dracut module.

if [[ $1 == --debug ]]; then
	set -x
	PS4='${BASH_SOURCE}@${LINENO}(${FUNCNAME[0]-}): '
	shift
fi

if [[ -f /etc/sysconfig/kdump ]]; then
	# shellcheck source=/dev/null
	. /etc/sysconfig/kdump
fi

[[ $dracutbasedir ]] || dracutbasedir=/usr/lib/dracut
# shellcheck source=/dev/null
. "$dracutbasedir"/dracut-functions.sh
# shellcheck source=SCRIPTDIR/kdump-lib.sh
. /lib/kdump/kdump-lib.sh
# shellcheck source=SCRIPTDIR/kdump-logger.sh
. /lib/kdump/kdump-logger.sh

#initiate the kdump logger
if ! dlog_init; then
	echo "mkfadumprd: failed to initiate the kdump logger."
	exit 1
fi

KDUMP_TMPDIR="$(mktemp -d -t mkfadumprd.XXXXXX)"
[ -d "$KDUMP_TMPDIR" ] || perror_exit "mkfadumprd: mktemp -d -t mkfadumprd.XXXXXX failed."
MKDUMPRD_TMPMNT="$KDUMP_TMPDIR/target"
# shellcheck disable=SC2154 # known issue of shellcheck https://github.com/koalaman/shellcheck/issues/1299
trap '
    ret=$?;
    is_mounted $MKDUMPRD_TMPMNT && umount -f $MKDUMPRD_TMPMNT;
    [[ -d $KDUMP_TMPDIR ]] && rm --one-file-system -rf -- "$KDUMP_TMPDIR";
    exit $ret;
    ' EXIT

# clean up after ourselves no matter how we die.
trap 'exit 1;' SIGINT

# shellcheck source=SCRIPTDIR/kdump-lib-dracut.sh
. /lib/kdump/kdump-lib-dracut.sh

mkfadumprd "$@"
