#!/bin/bash

inst "/bin/date" "/bin/date"
inst "/bin/sync" "/bin/sync"
inst "/usr/bin/reboot" "/bin/reboot"
inst "/sbin/makedumpfile" "/sbin/makedumpfile"
inst "/etc/kdump.conf" "/etc/kdump.conf"
inst "$moddir/kdump-lib.sh" "/lib/kdump-lib.sh"
inst_hook pre-pivot 01 "$moddir/kdump_localfs.sh"

