#!/bin/bash

inst "/bin/date" "/bin/date"
inst "/bin/sync" "/bin/sync"
inst "/usr/bin/reboot" "/bin/reboot"
inst "/sbin/makedumpfile" "/sbin/makedumpfile"
inst_hook pre-pivot 01 "$moddir/kdump_localfs.sh"

